In [51]:
import torch
import numpy as np

# Torch and Numpy

In [52]:
numpy_a = np.array([1,2,3])
numpy_a

array([1, 2, 3])

In [53]:
torch_a = torch.Tensor([4,5,6])
torch_a

tensor([4., 5., 6.])

In [54]:
torch_a = torch.Tensor(numpy_a)
torch_a

tensor([1., 2., 3.])

In [55]:
numpy_a.shape

(3,)

In [56]:
torch_a.size()

torch.Size([3])

# tensor requires_grad 

In [57]:
torch_a.requires_grad

False

In [58]:
torch_a.requires_grad = True
torch_a.requires_grad

True

In [59]:
with torch.no_grad():
    print((torch_a**2).requires_grad)

False


# torch.cat

In [76]:
b = torch.Tensor(1,2,3,3)
print(b)
b.size()

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])


torch.Size([1, 2, 3, 3])

In [61]:
c = torch.Tensor(1,2,3,3)
c.size()

torch.Size([1, 2, 3, 3])

In [62]:
concat = torch.cat([b,c],1)
concat.size()

torch.Size([1, 4, 3, 3])

In [63]:
concat = concat.view(1,4,-1)
concat.size()

torch.Size([1, 4, 9])

# Torch random

## torch.randint()
https://pytorch.org/docs/master/generated/torch.randint.html

In [64]:
random_arr = torch.randint(0,10,(1,3,4,4))
random_arr

tensor([[[[2, 1, 8, 0],
          [1, 8, 2, 5],
          [5, 8, 8, 6],
          [7, 7, 3, 0]],

         [[3, 8, 1, 9],
          [3, 9, 7, 4],
          [0, 0, 6, 9],
          [7, 7, 7, 1]],

         [[2, 6, 4, 0],
          [7, 6, 5, 1],
          [3, 3, 7, 8],
          [6, 5, 2, 3]]]])

## torch.randn()
https://pytorch.org/docs/master/generated/torch.randn.html

In [65]:
random_arr = torch.randn((1,3,4,4))
random_arr

tensor([[[[-0.2777,  0.7949,  1.0738, -0.7697],
          [-0.9539,  1.0130, -0.2848, -0.1553],
          [ 0.3457,  1.0507, -1.4924, -0.0624],
          [-0.9764, -1.5395,  0.1191,  1.1484]],

         [[-0.5461,  1.0379,  0.2433, -1.1163],
          [-0.5524, -1.4682, -1.1498, -1.5580],
          [-0.0870, -0.4279,  0.4006,  0.6801],
          [-1.3486, -0.3051, -1.4674,  0.0219]],

         [[-1.3158,  0.0095, -1.8524, -1.5192],
          [ 0.6938, -0.6603, -1.2960, -0.2038],
          [ 0.3414, -0.2039, -0.7154,  0.3375],
          [-0.7584,  0.6113, -1.2413, -1.3319]]]])

# view and transpose

In [66]:
temp1 = torch.randint(0,10,(2,4,4))
temp1

tensor([[[9, 8, 9, 6],
         [5, 5, 3, 1],
         [2, 1, 8, 5],
         [1, 4, 4, 3]],

        [[7, 3, 6, 2],
         [2, 4, 4, 5],
         [5, 8, 6, 3],
         [3, 8, 6, 2]]])

In [67]:
temp2 = temp1.view(2,16)
temp2

tensor([[9, 8, 9, 6, 5, 5, 3, 1, 2, 1, 8, 5, 1, 4, 4, 3],
        [7, 3, 6, 2, 2, 4, 4, 5, 5, 8, 6, 3, 3, 8, 6, 2]])

In [68]:
temp2[0,1] = 11
temp2

tensor([[ 9, 11,  9,  6,  5,  5,  3,  1,  2,  1,  8,  5,  1,  4,  4,  3],
        [ 7,  3,  6,  2,  2,  4,  4,  5,  5,  8,  6,  3,  3,  8,  6,  2]])

In [69]:
temp1

tensor([[[ 9, 11,  9,  6],
         [ 5,  5,  3,  1],
         [ 2,  1,  8,  5],
         [ 1,  4,  4,  3]],

        [[ 7,  3,  6,  2],
         [ 2,  4,  4,  5],
         [ 5,  8,  6,  3],
         [ 3,  8,  6,  2]]])

In [70]:
temp1 = torch.randint(0,10,(2,4))
temp1

tensor([[8, 8, 4, 1],
        [9, 4, 5, 1]])

In [71]:
temp2 = temp1.transpose(0,1)
temp2

tensor([[8, 9],
        [8, 4],
        [4, 5],
        [1, 1]])

In [72]:
temp1.size()

torch.Size([2, 4])

In [73]:
temp2.size()

torch.Size([4, 2])